[SERVICE]
    flush           5
    daemon          off
    log_level       info
    parsers_file    parsers.conf

[INPUT]
    name              systemd
    tag               journal
    read_from_tail    on
    strip_underscores on
    db                /var/lib/fluent-bit/journal.db

[FILTER]
    name    lua
    match   journal
    script  /etc/fluent-bit/loki-labels.lua
    call    enrich

[OUTPUT]
    name              loki
    match             journal
    host              192.168.91.107
    port              3100
    labels            job=journal_logs
    label_keys        $app,$unit,$instance,$level
    structured_metadata_map_keys  $BOOT_ID,$TRANSPORT,$PRIORITY,$PID,$UID,$GID,$COMM,$EXE,$CMDLINE,$TID,$CAP_EFFECTIVE,$SYSLOG_IDENTIFIER,$SYSLOG_FACILITY,$SYSLOG_TIMESTAMP,$SYSLOG_PID,$SYSTEMD_UNIT,$SYSTEMD_USER_UNIT,$SYSTEMD_SLICE,$SYSTEMD_CGROUP,$SYSTEMD_INVOCATION_ID,$CODE_FILE,$CODE_LINE,$CODE_FUNC,$MACHINE_ID,$MESSAGE_ID,$INVOCATION_ID,$TIMESTAMP_MONOTONIC,$TIMESTAMP_BOOTTIME,$SOURCE_REALTIME_TIMESTAMP,$RUNTIME_SCOPE,$JOB_ID,$JOB_TYPE,$JOB_RESULT,$NM_LOG_DOMAINS,$NM_LOG_LEVEL,$NM_DEVICE
    line_format       key_value
    drop_single_key   on
    auto_kubernetes_labels off
